### ISSUE TITLE
Enhance documentation to show how to use ecs_services

### ISSUE THREAD

**Issue by simplesteph** [simple-machines/ansible-template#17]

**Comment by simplesteph** [comment]
i.e. in roles/dev/vars/main.yml, add the following
```

ecs_services:
  - name: "{{ application_name }}"
    task: # A service always has a single task, which is mapped here.
      containers: # A task can have multiple containers
      - name: "{{ application_name }}"
        cpu: "{{ resources_for_instance_type.cpu }}"
        memory: "{{ resources_for_instance_type.memory }}"
        environment:
          - name: "AUTO_TAMALE_REPLY_TO_QUEUE"
            value: "betReplyQ"
          - name: "TAMALE_CONSUMER_TOKEN"
            value: "{{ tamale_consumer_token }}"
          - name: "TAMALE_BET_STREAM"
            value: "fixture"
          - name: "TAMALE_REQUEST_QUEUE"
            value: "tamale_operations_request_q"
          - name: "SPRING_RABBITMQ_HOST"
            value: "{{ spring_rabbitmq_host }}"
          - name: "SPRING_RABBITMQ_PORT"
            value: "5672"
          - name: "SPRING_RABBITMQ_USERNAME"
            value: "{{ spring_rabbitmq_username }}"
          - name: "SPRING_RABBITMQ_PASSWORD"
            value: "{{ spring_rabbitmq_password }}"
```

in which you can reference secret variables too
