### ISSUE TITLE
ecs_environment_variables will not be merged if they exists in different `var/main.yml` files

### ISSUE THREAD

**Issue by don41382** [simple-machines/ansible-template#46]
I am settings in `infra/vars/main.yml` my general username/password from the `secret.yml`

*infra/vars/main.yml*
```
ecs_environment_variables:
  - name: "PLAY_SECRET"
    value: "{{ play_secret }}"
  - name: "API_USERNAME"
    value: "{{ api_username }}"
  - name: "API_PASSWORD"
    value: "{{ api_password }}"
```

for dev and prod I need more specific ECS environment variables:

*dev/vars/main.yml*
```
ecs_environment_variables:
  - name: "KAFKA_DEV_URL"
    value: "192.168.0.1"
```

It would be nice if the ansible template would merge both ecs_environment_variables. DEV would override existing variables inside of infra. e.g.:
```
ecs_environment_variables:
  - name: "PLAY_SECRET"
    value: "{{ play_secret }}"
  - name: "API_USERNAME"
    value: "{{ api_username }}"
  - name: "API_PASSWORD"
    value: "{{ api_password }}"
  - name: "KAFKA_DEV_URL"
    value: "192.168.0.1"
```

**Comment by simplesteph** [comment]
In infra you would do:

```
ecs_environment_variables:
  - name: "PLAY_SECRET"
    value: "{{ play_secret }}"
  - name: "API_USERNAME"
    value: "{{ api_username }}"
  - name: "API_PASSWORD"
    value: "{{ api_password }}"
  - name: "KAFKA_URL"
    value: "{{ kafka_url }}"
```

and then define this in dev.yml

`kafka_url: "192.168.0.1"`
