### ISSUE TITLE
asg_desired_capacity should only bet set if the ASG doesn't exist

### ISSUE THREAD

**Issue by simplesteph** [simple-machines/ansible-template#8]
otherwise it will terminate instances if desired capacity < actual capacity. 

See the following for a fix:

```
- name: Retrieve current Auto Scaling Group properties
  command: "aws --region {{ ansible_env.AWS_REGION }} autoscaling describe-auto-scaling-groups --auto-scaling-group-names {{ ecs_cluster_name }}"
  register: asg_properties_result

- name: Set asg_properties variable from JSON output if the Auto Scaling Group already exists
  set_fact:
    asg_properties_desired_capacity: "{{ (asg_properties_result.stdout | from_json).AutoScalingGroups[0].DesiredCapacity }}"
  when: (asg_properties_result.stdout | from_json).AutoScalingGroups | count


- name: create autoscaling group
  ec2_asg:
    name: "{{ ecs_cluster_name }}"
    launch_config_name: "{{ app_launch_config['name'] }}"
    min_size: "{{ min_size }}"
    max_size: "{{ max_size }}"
    desired_capacity: "{{ asg_properties_desired_capacity | default(default_capacity) }}"
```
